### ISSUE TITLE
Mini-cart Sidebar Not Loading When Using WooCommerce Payfast Payment Gateway

### ISSUE THREAD

**Issue by upwardmomentum84** [woocommerce/woocommerce-gateway-payfast#202] opened 2024-03-04 20:37 UTC
### Describe the Bug

When a site has WooCommerce set up with WooCommerce Payfast Gateway, the mini-cart sidebar overlay is blank.

### To Reproduce

1. Install and activate WooCommerce as well as WooCommerce Payfast Gateway plugins.
2. Setup the Payfast Gateway and enable in WooCommerce settings as a payment method.
3. Add a Mini-cart block to a page
4. View the live page.
5. Add at least one item to your cart.
6. Click the mini-cart icon to see the sidebar.

### Screenshots

This is what it looks like:

![CleanShot 2024-03-04 at 15 28 16](https://github.com/woocommerce/woocommerce-gateway-payfast/assets/93800099/84dde397-a325-4c54-8c4d-4450f8dd118a)

### Expected Behavior

The side bar to look like this, showing the items in the cart:

![CleanShot 2024-03-04 at 15 34 48](https://github.com/woocommerce/woocommerce-gateway-payfast/assets/93800099/416d3c6b-2182-4946-b23e-bc96eafaaf17)

### Environment

- WooCommerce Version 8.6.1
- WooCommerce Payfast Gateway 1.6.1
- Any theme. I replicated using Meraki as well as Twenty Twenty.

### Additional Details

Reported here: 7784397-zd-a8c

**Comment by jeffpaul** [comment] 2024-03-05 16:15
@Sidsector9 as this issue is reported against the version where #190 was released, it seems like there's a scenario missing in the WC Blocks compat work... can you check on this (potentially alongside our QA team)?

**Comment by upwardmomentum84** [comment] 2024-03-05 19:10
Just noting in case it makes a difference, when I configured the Payfast gateway on my test site, I put in random information in the Payfast configuration to allow me to fully enable it. Not sure if I had used valid information if this would still be an issue. I suspect it wouldn't make a difference though.

Also, if we can update the user when this is fixed that would be great - 7784397-zd-a8c

**Comment by Sidsector9** [comment] 2024-03-06 08:33
Hi @upwardmomentum84 I am unable to reproduce this issue on my end.

I have tested this with the correct as well as incorrect credentials with the following themes: 2020, 2024 and Storefront. Please see the video and the images below:

### Video (Storefront)

https://github.com/woocommerce/woocommerce-gateway-payfast/assets/17757960/bf2e4d1e-7905-4a56-88f8-ff978f0d877b

### Screenshots (2024 and 2020)

<img width="1571" alt="Screenshot 2024-03-06 at 1 58 17 PM" src="https://github.com/woocommerce/woocommerce-gateway-payfast/assets/17757960/d03b93f6-6dae-476c-9815-06c924d7e454">
<img width="1416" alt="Screenshot 2024-03-06 at 2 00 28 PM" src="https://github.com/woocommerce/woocommerce-gateway-payfast/assets/17757960/8eb4a8bc-b8da-4c50-a3e3-97b15c4ed251">

**Comment by upwardmomentum84** [comment] 2024-03-06 13:11
I did some more testing and found this issue only happens on WordPress.com sites as shown in this screen recording: 

https://github.com/woocommerce/woocommerce-gateway-payfast/assets/93800099/d38cbc77-240d-4215-bd59-d40d452bb56e

I tested on a local test site and the issue does not occur there.

**Comment by Sidsector9** [comment] 2024-03-07 15:33
Thanks for the additional info @upwardmomentum84.

Adding a video here that shows the issue only occurs when installing directly from the plugins repo - https://drive.google.com/file/d/1EYnnNg56YRpA7AbJI7sG4VvUQyenOepx/view?usp=sharing

**Comment by vikrampm1** [comment] 2024-05-22 11:53
@Sidsector9 I am moving this back to To Do. Please review/pick it back up when you resume looking into this. And, please reach out if we are still awaiting for any further information from the author.

**Closed as completed** 2024-06-24 14:21 UTC
Labels: bug
