### ISSUE TITLE
Orders stuck at Pending Payment when using reverse proxy

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-payfast#11] opened 2019-10-12 14:27 UTC
**Describe the bug** 
WooCommerce PayFast plugin validates if ITN payment notification came from a legitimate source by comparing source IP with `payfast.co.za` servers. This automatically breaks payment notifications on all servers that use reverse proxy such as Cloudflare.

As a workaround, we're recommending the customers disable IP filtering with a custom code snippet which is neither secure nor easy to implement:

https://github.com/woocommerce/woocommerce-gateway-payfast/blob/master/includes/class-wc-gateway-payfast.php#L1227

I'd bring it up with the PayFast team to see if there's a better security mechanism we can use.

**To Reproduce**
1. Set up Cloudflare proxy on the server;
2. Purchase any product using Payfast payment gateway
3. Observe order status is still Pending Payment even though the payment went through

**Expected behavior**
Order status changes to Processing after successful payment.

**Comment by corsonr** [comment] 2019-11-24 11:08
Any news?

**Comment by zwiesman31** [comment] 2019-12-22 15:08
CC: @luizreis

**Comment by madeincosmos** [comment] 2020-01-14 16:05
One more user possibly affected by this in 2629462-zen

**Comment by RiaanKnoetze** [comment] 2020-01-29 10:54
Adding 2416714-zen

**Comment by dbfx** [comment] 2020-02-27 16:59
Had this start happening today randomly - any IP changes happen?

**Comment by iamdharmesh** [comment] 2022-06-15 08:12
I am not able to reproduce this issue. moving this to Backlog for now until we have some new reports for the same.

Thanks

**Comment by jeffpaul** [comment] 2022-11-03 14:47
Closing as we're unable to replicate, if additional replication steps can be confirmed then please re-open and we'll continue triaging then... thanks!

**Closed by jeffpaul** 2022-11-03 14:47 UTC
Labels: priority: high, [Status] Blocked, type: technical debt
