### ISSUE TITLE
Add the ability for PayFast to show and store CC data when the checkout is at 0.00 with Subscriptions free trials

### ISSUE THREAD

**Issue by nixiack** [woocommerce/woocommerce-gateway-payfast#21] opened 2020-08-04 20:24 UTC
**Is your feature request related to a problem? Please describe.**
When working with the Subscriptions product, PayFast disappears as an option when the cart shows 0.00 - for example a Free Trial that zeroes out the amount in the Cart.

**Describe the solution you'd like**
When there is a subscription in the cart that is 0.00, PayFast should show up to at least record the CC field information down for renewal payments.

**Describe alternatives you've considered**
This appears to be a limitation to PayFast only - when setting the free trial it does not show PayFast:

![Screenshot](https://d.pr/i/wMlxmq+)
Screenshot: https://d.pr/i/wMlxmq

When removing Free Trial it shows move to PayFast: 

![Screenshot](https://d.pr/i/gbGrvW+)
Screenshot: https://d.pr/i/gbGrvW

![Screenshot](https://d.pr/i/NsUk2L+)
Screenshot: https://d.pr/i/NsUk2L

**Additional context**
I know that from the [Subs documentation](https://docs.woocommerce.com/document/subscriptions/payment-gateways/#section-2) that there are a lot of limitations with PayFast but this is a big one; without the ability to store CC information on free trials it will cause a lot of users to probably abandon this gateway for something like Stripe, which allows for it.

**Comment by iamdharmesh** [comment] 2022-01-04 07:49
As mentioned here https://developers.payfast.co.za/docs#go_live, PayFast will not be able to process payments with an amount less than ZAR 5.00. So, users can able to save CC data for free trials only once PayFast supports a $0 transaction. (btw, I can see PayFast in the payment gateway list but I am not able to do payment successfully as getting error on the PayFast page)

![image](https://user-images.githubusercontent.com/10613171/148021746-e18a8a94-028a-41c4-aafc-607075e8c071.png)

**Just for note:** for https://github.com/woocommerce/woocommerce-gateway-payfast/issues/32 we also needed $0 transaction support.
@jeffpaul @dkotter I think I am blocked here, can you please help to suggest on this?

**Comment by jeffpaul** [comment] 2022-01-05 14:44
@iamdharmesh will do, we'll check with WooCommerce and their Payfast partners to see if we can get this updated on the Payfast side so we can resolve here in the extension... thanks!

**Comment by jeffpaul** [comment] 2022-01-14 22:49
@iamdharmesh we heard from @laurendavissmith that according to the PayFast docs they should already support a trial period at 0 for submissions.  See more here: https://developers.payfast.co.za/docs#tokenization

**Comment by iamdharmesh** [comment] 2022-01-17 07:53
Hi @jeffpaul, Thanks for pointing out documentation related to tokenization. 
As I mentioned in my last comment I was getting errors in doing payment of `R0.00`, I am still getting it but after checking further on it, I found that after a few seconds of error, Payfast automatically redirects to the store with SUCCESS. Please check the video for more details. **Not sure if this behavior is due to the sandbox environment.** maybe on live env this should work as expected. 

https://user-images.githubusercontent.com/10613171/149726846-24b114b8-8506-4080-9646-226231800c22.mp4

As Payfast gateway is already showing in the list during checkout for the `0.00` amount, the reported issue is not reproduce for me anymore (ignoring error on payment considering sandbox). @nixiack can you please help to check if you can still reproduce the issue at your end. If can't then I think we can proceed with closing this issue.

Thanks.

**Comment by iamdharmesh** [comment] 2022-02-01 04:28
I contacted **PayFast** support team about this error on the `Sandbox` environment, they have replied that we can ignore the errors on a sandbox, it will not impact live env. 
@ankitguptaindia I am not able to reproduce this issue. Can you please help to check this on your side once?

Thanks.

**Closed** 2022-08-01 20:37 UTC
Labels: priority: high, needs feedback, type: enhancement
