### ISSUE TITLE
Better Error Handling/Flow for Expired Cards

### ISSUE THREAD

**Issue by SiobhyB** [woocommerce/woocommerce-gateway-payfast#32] opened 2020-12-07 15:22 UTC
**Describe the bug**

In 3553380-zen, a user reported confusion as subscribers were being led to the following error at checkout, when attempting to manually renew a subscription:

```
Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements.
```

The subscribers had expired cards and, given [PayFast's limitations with Subscriptions](https://docs.woocommerce.com/document/subscriptions/payment-gateways/), it wouldn't be possible for them to update the card on file. That said, the error that displayed is confusing and unhelpful in this scenario.

**Expected behavior**

If the option to update the card on file isn't available, then better error messaging and directions for subscribers to take would be the next best possibility. A notice about the payment gateway's limitations and steps to cancel their subscription (so that they can re-purchase) would likely be enough.

**Comment by PallookaJ** [comment] 2020-12-08 03:36
This bug does not present on a staging site, only a live site. On a staging site the payment gateway is shown as is expected. This leads me to believe this is a bug in either woocommerce core or woocommerce subscriptions and not in the payfast plugin.

**Comment by jacoswan** [comment] 2020-12-08 12:55
@PallookaJ - I'm able to recreate it on a staging site. 

Using Payfast sandbox, I renewed once as normal, then changed the password in Payfast sandbox before triggering the renewal, causing a failed renewal. I emailed the user the invoice with link to renew, but when following the link from the emailed invoice, this notice appears: 

![image](https://user-images.githubusercontent.com/15178758/101486267-0eefaa80-3965-11eb-984e-e4f8be9bb234.png)

Something similar is [described in this open issue](https://github.com/woocommerce/woocommerce-gateway-payfast/issues/5), and @dwainm eludes to there being next steps? 

> We should handle this in a way that gives the admin/shop_manager a better idea of the steps to take next.

Are these issues related, and what might those next steps be?

**Comment by PallookaJ** [comment] 2020-12-08 13:10
@jacoswan What happens when you navigate to the My Account area as that user and initiate the payment of the failed order from there? On our staging it then shows the gateway as payment option. On live it doesn't matter which way round you navigate to the checkout for the failed order you always get the "no payment methods" message.

@dwainm's issue might be related but I'm not seeing any 400 errors in our logs though.

**Comment by jacoswan** [comment] 2020-12-08 15:13
Ah, yes. On my staging site Subscriptions is live, and accessing the order via My Account » Orders » Pay still doesn't offer the gateway as an option. I'll test it more.

**Comment by PallookaJ** [comment] 2020-12-08 15:22
So if you put Subscriptions in staging mode you'll see that it works perfectly. That's why I feel it could possibly be a Subscriptions bug

**Comment by jacoswan** [comment] 2020-12-09 06:55
Thanks, @PallookaJ. The [Subscriptions GH](https://github.com/woocommerce/woocommerce-subscriptions/issues/3917) added details, tl;dr - what @SiobhyB said 😓 can the error message be clarified for this situation - would this count as an enhancement.. and would it be to Payfast or Subs?

**Comment by JDSymington** [comment] 2021-03-31 19:34
I'm having this exact same issue on my live site.

One workaround I can think of is to cancel the users' subscription and let them go through the checkout process again. This is not ideal.

Another way would be to provide users with a link to update their card details.

According to the PayFast developer pages:
"**Update card details**
Provide buyers with a link to update their card details on a Recurring Billing subscription or Tokenization charges. This link will redirect them to PayFast in order to perform the update securely.
**Example:**
https://www.payfast.co.za/eng/recurring/update/{token}?return={return}"

Is there a way to retrieve the logged in user's token to generate this URL for them and place it in a button?
In theory it should be easy but I just don't have enough knowledge in this area.

**Comment by JDSymington** [comment] 2021-10-03 16:05
Hi @SiobhyB. Did you end up finding a way around this problem?

**Comment by SiobhyB** [comment] 2021-10-08 05:14
@JDSymington, at the time, I'm afraid the only workaround was to guide subscribers to cancel their existing subscriptions when their cards expire. They can then re-subscribe using the new credit/debit card. There might be a way to automate emails that send when cards expire, I know [AutomateWoo has some related and promising functionality](https://automatewoo.com/docs/triggers/saved-card-expiry-notifications/). 

If you have a paid extension, I'd recommend getting in touch with WooCommerce's support team to figure out whether there's other options, too: https://woocommerce.com/contact-us/

**Comment by JDSymington** [comment] 2021-10-15 09:38
@SiobhyB that is unfortunate.
By forcing customers to cancel their subscription there is a much higher probability that they won't subscribe again and you loose a paying customer.

**Comment by Viva57** [comment] 2021-12-10 08:32
Hi all. This issue is affecting my membership site. My only option is to cancel the subscription on the user's behalf and ask them to resubscribe. It is a subpar experience and ultimately not sustainable. What options do we have to get Woocommerce/Payfast to get this fixed?

**Comment by jeffpaul** [comment] 2021-12-21 17:54
After discussion it sounds like the most ideal approach here would be for Payfast to support a $0 transaction so that the extension could be enhanced to add proper support for `subscription_payment_method_change_customer`.  Is that an accurate and complete summary @iamdharmesh?

**Comment by iamdharmesh** [comment] 2021-12-22 04:15
Yes @jeffpaul .

**Comment by Viva57** [comment] 2022-02-14 09:23
I've been following progress on this issue since my earlier comment (Dec 10). Looking at https://github.com/woocommerce/woocommerce-gateway-payfast/pull/63 it seems like a solution has been implemented, reviewed and approved. What needs to happen before this fix is released?

**Comment by ankitguptaindia** [comment] 2022-02-14 13:28
Hi @Viva57 This issue is in QA phase and still needs some more steps in our process like QA, Code Review (Woo team),  Regression, UAT/Demo, Smoke Testing.
I am adding this to Todo list on priority for the earliest release.

**Comment by Viva57** [comment] 2022-04-28 17:19
Hi all. It's quite a few weeks later and I'd like to check in: When will this fix be released. 

From what I can tell, quite a bit of progress have been made in the meantime. I (and I'm sure many others) are desperately waiting for this to be released. In the absence of this fix, we're losing subscribers.

**Comment by jeffpaul** [comment] 2022-04-28 18:00
@Viva57 this issue and respective PR are one of many that the engineering team is working on across multiple extensions.  I'll see if I can nudge this one forward.

**Comment by ankitguptaindia** [comment] 2022-05-09 13:25
**Update -**  Above issue is addressed in connected PR. New customers' reports of this issue can be tested/verify with this **Development version** of the plugin.

[woocommerce-gateway-payfast.zip](https://github.com/woocommerce/woocommerce-gateway-payfast/files/8652067/woocommerce-gateway-payfast.zip)



**_Please Note that this is Dev version of the plugin file and ONLY has fixes related to the above issue so other fixes might not work with this dev version of the plugin. It is also recommended that, Don't use this plugin file on the Production/Live site. This is just for testing purposes only_**

**Closed** 2022-06-08 15:09 UTC
Labels: priority: high, type: bug
