### ISSUE TITLE
Plugin not compatible with the latest block based checkout

### ISSUE THREAD

**Issue by PureandWholeStore** [woocommerce/woocommerce-gateway-payfast#46] opened 2021-07-30 13:48 UTC
**Describe the bug**
The plugin not compatible with the latest block based checkout.
Tested on WP 5.8 & WC 5.5.2

![Screen Shot 2021-07-30 at 15 37 57](https://user-images.githubusercontent.com/71368368/127662003-c07e9496-f23f-4421-88c1-949152079bf1.png)
![Screen Shot 2021-07-30 at 15 38 03](https://user-images.githubusercontent.com/71368368/127662029-85f61ec7-946b-4eaa-b400-ad08616d9a37.png)
![Screen Shot 2021-07-30 at 15 36 06](https://user-images.githubusercontent.com/71368368/127662058-f316aca7-f3dc-4028-a613-92ba40e77355.png)
![Screen Shot 2021-07-30 at 15 36 27](https://user-images.githubusercontent.com/71368368/127662075-9f180aad-2bb8-4013-9723-a5658bf6abdf.png)
![Screen Shot 2021-07-30 at 15 33 57](https://user-images.githubusercontent.com/71368368/127662083-d8cad297-4ad2-4aad-8dd0-2adf2f255c3a.png)
![Screen Shot 2021-07-30 at 15 36 06](https://user-images.githubusercontent.com/71368368/127662523-7d642840-ce9f-4d8e-875e-20911013ad72.png)

**Expected behavior**
Should display during the checkout process

**Environment (please complete the following information):**
 - WordPress Version 5.8 
 - WooCommerce Version 5.5.2
 - PayFast Plugin Version 1.4.19
 - Browser [e.g. chrome, safari] and Version Firefox 90.0
 - Any other plugins installed alot :)

**Comment by PureandWholeStore** [comment] 2021-07-30 13:50
![Screen Shot 2021-07-30 at 15 50 08](https://user-images.githubusercontent.com/71368368/127662853-a93c5b45-649e-45cb-a785-5b69057e34ad.png)

**Comment by Aljullu** [comment] 2021-09-06 17:44
Thanks for opening this issue @PureandWholeStore!

I was able to reproduce it. It looks like the version of WooCommerce PayFast Gateway that is distributed in WooCommerce.com and WordPress.org doesn't include the `build` directory, which contains the script that registers the payment method in blocks.

However, things work fine in the development version directly built from the repo.

@ismaeldcom @dwainm any idea what might be the issue here? Is there anything I can do to help?

**Comment by ismaeldcom** [comment] 2021-09-07 10:16
Hi @Aljullu! Thanks for reviewing the issue, Axiom team will take care of PayFast from now on.
There is no `@woocommerce/axiom` yet, so cc @LCmry instead.

**Comment by Aljullu** [comment] 2021-09-08 08:18
Heads-up that I removed PayFast from the [list of supported payment gateways](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) in the Cart & Checkout blocks status page. @LCmry, will you be able to add it back (or ping me) once this issue is fixed? Thanks!

**Comment by cadic** [comment] 2021-10-19 08:31
The `composer archive` command is respecting `.gitignore`, that's why "build" directory was excluded from the zip.

Also, when in Sandbox mode and empty Merchant ID/Key/Passcode, Payfast method was globally disabled.

Fixing all of this in the PR.

**Comment by csmcneill** [comment] 2021-10-26 18:32
4403078-zen is using PayFast with WooCommerce Blocks; they can accept payment, but the order statuses do not successfully change after payment is accepted. Could these be related?

**Comment by haybelanger** [comment] 2021-11-16 15:27
@ankitguptaindia Ive moved this to the Smoke Test column and reassigning to you.

**Comment by ankitguptaindia** [comment] 2021-11-17 08:43
@haybelanger 

Smoke Test Approved. 
**Next Step-** Ready to Merge.

**Closed as completed** 2021-11-17 21:24 UTC
Labels: bug
