### ISSUE TITLE
Cloudflare triggers PF_ERR_BAD_SOURCE_IP

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-payfast#7] opened 2019-07-31 02:08 UTC
This came in via 2234571-zen

The PayFast extension fails on sites hosted behind Cloudflare (on Flywheel) because the source IP rotates. Payfast confirms. The error is below. Only commenting out these lines in the plugin allows it to work. Status report provided is generic for privacy reasons.

```php
// Verify source IP (If not in debug mode) 
if ( ! $payfast_error && ! $payfast_done && $this->get_option( 'testmode' ) != 'yes' ) { 
    $this->log( 'Verify source IP' );

    if ( ! $this->is_valid_ip( $_SERVER['REMOTE_ADDR'] ) ) { 
        $payfast_error = true; 
        $payfast_error_message = PF_ERR_BAD_SOURCE_IP; 
    } 
}
```

ERROR FROM LOGS HERE: 
07-17-2019 @ 10:49:27 - 
---------- 
PayFast ITN call received 
---------- 
07-17-2019 @ 10:49:27 - Get posted data 
07-17-2019 @ 10:49:27 - PayFast Data: Array 
( 
[m_payment_id] => 27724 
[pf_payment_id] => 19924549 
[payment_status] => COMPLETE 
[item_name] => Fancy Schmancy - 27724 
[item_description] => New order from Fancy 
[amount_gross] => 1200.00 
[amount_fee] => -50.60 
[amount_net] => 1149.40 
[custom_str1] => wc_order_P894HKimqn61E 
[custom_str2] => WooCommerce/3.6.5; https://www.myawersomsiteblahblahblahblahnotarealURL.com 
[custom_str3] => 27724 
[custom_str4] => 
[custom_str5] => 
[custom_int1] => 
[custom_int2] => 
[custom_int3] => 
[custom_int4] => 
[custom_int5] => 
[name_first] => Dude 
[name_last] => Maloney 
[email_address] => sdfkjljkfds@sdflkjsfd.com 
[merchant_id] => 52626182 
[signature] => af9a622f8sdfdsfsdf8f33160602b2 
)

07-17-2019 @ 10:49:27 - Verify security signature 
07-17-2019 @ 10:49:27 - Signature = valid 
07-17-2019 @ 10:49:27 - Verify source IP 
07-17-2019 @ 10:49:27 - Valid IPs: 
Array 
( 
[0] => 43.74.179.210 
[1] => 43.74.179.211 
[2] => 43.74.179.217 
[3] => 43.74.179.218 
[4] => 43.97.145.156 
[5] => 43.74.179.193 
[6] => 43.74.179.194 
[7] => 43.74.179.195 
[8] => 43.74.179.196 
[9] => 43.74.179.197 
[10] => 43.74.179.200 
[11] => 43.74.179.201 
[12] => 43.74.179.203 
[13] => 43.74.179.204 
[16] => 43.74.179.212 
[17] => 43.97.145.145 
[18] => 43.97.145.148 
[19] => 43.97.145.149 
[21] => 43.97.145.150 
)

07-17-2019 @ 10:49:27 - Error occurred: Bad source IP address 
07-17-2019 @ 10:49:27 - 
---------- 
End ITN call 
----------

**Comment by RiaanKnoetze** [comment] 2019-08-15 10:41
Bumping the status to critical, if payments are fundamentally broken on a website that runs Cloudflare + PayFast, it undermines the _ecommerce_ site as a whole.

**Comment by allendav** [comment] 2019-09-13 21:00
@RiaanKnoetze - is cloudflare used by a majority of payfast sites?

**Comment by allendav** [comment] 2019-09-13 21:03
@dwainm - please investigate a fix for this

**Comment by RiaanKnoetze** [comment] 2020-02-14 07:22
Apologies @allendav - I missed your question here. Cloudflare is only popular for the bigger South African websites 🙂

With that said, a new report just surfaced in 2702282-zen where the user reported the same error but mentions that they _don't_ have Cloudflare active. They're currently with Bluehost we're currently ruling out whether the must-use caching plugins might be at play.

**Comment by dbfx** [comment] 2020-03-02 12:36
Any word on this? I'm having it on a wordpress.com site behind cloudflare

**Comment by RHSkinner** [comment] 2020-06-09 12:04
Is there any update on this issue? I seem to be encountering the same problem.

**Comment by Spartex** [comment] 2020-09-25 15:50
Is there a fix for this Cloudflare ITN as it still is happening despite adding "HTTP_CF_Connecting_IP"?

**Comment by iamdharmesh** [comment] 2022-06-15 08:14
I am not able to reproduce this issue. moving this to Backlog for now until we get some new reports for the same.

Thanks

**Comment by jeffpaul** [comment] 2022-11-03 14:49
Closing as we're unable to replicate, if additional replication steps can be confirmed then please re-open and we'll continue triaging then... thanks!

**Closed by jeffpaul** 2022-11-03 14:49 UTC
Labels: priority: high, [Status] Blocked, type: bug
